apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: quarkus-app-templates
  description: Quarkus application templates for Red Hat Developer Hub
spec:
  targets:
    - ./templates/quarkus-app/template.yaml
